export interface LocationData {
    companyUniqueID: string;
    isActive: boolean;
    createdDate: Date | null;
    modifiedDate: Date;
    hasExpiry: boolean | null;
    firstNotificationDate: Date | null;
    secondNotificationDate: Date | null;
    eplicable: boolean;
    applicable: boolean | null;
    department: string | null;
    departmentId: number | null;
    positionId: number | null;
    position: string | null;
    noStaffNeeded: number | null;
    isManager: boolean | null;
    payRateId: number | null;
    payRate: number | null;
    payRateString: string;
    maxPayRate: number | null;
    maxPayRateString: string;
    payrateYear: number | null;
    payRateYearId: number;
    payType: string | null;
    maxPayType: string | null;
    locationId: number;
    location: string;
    locationType: string;
    latitude: number;
    longitude: number;
    locationAddress: string;
    qualificationId: number | null;
    qualification: string | null;
    qualificationType: string | null;
    specialLicenseId: number | null;
    specialLicense: string | null;
    trainingId: number | null;
    training: string | null;
    evaluation: string | null;
    evaluationId: number | null;
}
