export interface AspNetUserModel {
    id: string;
    companyUniqueID: number | null;
    email: string;
    emailConfirmed: boolean;
    passwordHash: string | null;
    securityStamp: string | null;
    phoneNumber: string;
    phoneNumberConfirmed: boolean;
    twoFactorEnabled: boolean;
    lockoutEndDateUtc: Date | null;
    lockoutEnabled: boolean;
    accessFailedCount: number;
    userName: string;
    password: string | null;
    isActive: boolean | null;
    roleId: number | null;
    firstName: string;
    lastName: string;
    createdBy: number | null;
    createdDate: Date | null;
    modifiedBy: number | null;
    modifiedDate: Date | null;
    address: string | null;
    isEmailDeleted: boolean | null;
    address2: string | null;
    city: string | null;
    stateId: number | null;
    countryId: number | null;
    zipcode: string | null;
    nickName: string | null;
    isAllowuserInvoice: boolean | null;
    userWebsite: string | null;
    profilePicture: string | null;
    profilePicturePath: string | null;
    profilePictureUploadedFileName: string | null;
    isEmployee: boolean | null;
    isCMSuser: boolean | null;
    navigateToken: string | null;
}

export interface AspNetUserAlt {
    id: string;
    companyUniqueID: string | null;
    email: string;
    emailConfirmed: boolean;
    passwordHash: string | null;
    securityStamp: string | null;
    phoneNumber: string | null;
    phoneNumberConfirmed: boolean;
    twoFactorEnabled: boolean;
    lockoutEndDateUtc: string | null;
    lockoutEnabled: boolean;
    accessFailedCount: number;
    userName: string;
    password: string | null;
    isActive: boolean;
    roleId: string | null;
    firstName: string;
    lastName: string;
    createdBy: string | null;
    createdDate: string;
    modifiedBy: string | null;
    modifiedDate: string;
    address: string;
    isEmailDeleted: string | null;
    address2: string | null;
    city: string;
    stateId: number;
    countryId: number;
    zipcode: string;
    nickName: string | null;
    isAllowuserInvoice: string | null;
    userWebsite: string | null;
    profilePicture: string | null;
    profilePicturePath: string | null;
    profilePictureUploadedFileName: string | null;
    isEmployee: boolean;
    isCMSuser: boolean;
    navigateToken: string | null;
    b2CUserId: string;
}
